// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: interfaccia.proto

package interfaccia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// // messaggi,procedure e servizi remoti per Ring Election
type MessageElection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListIdPeer []string `protobuf:"bytes,1,rep,name=list_id_peer,json=listIdPeer,proto3" json:"list_id_peer,omitempty"`
}

func (x *MessageElection) Reset() {
	*x = MessageElection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaccia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageElection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageElection) ProtoMessage() {}

func (x *MessageElection) ProtoReflect() protoreflect.Message {
	mi := &file_interfaccia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageElection.ProtoReflect.Descriptor instead.
func (*MessageElection) Descriptor() ([]byte, []int) {
	return file_interfaccia_proto_rawDescGZIP(), []int{0}
}

func (x *MessageElection) GetListIdPeer() []string {
	if x != nil {
		return x.ListIdPeer
	}
	return nil
}

type ResultElection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPeers string `protobuf:"bytes,1,opt,name=id_peers,json=idPeers,proto3" json:"id_peers,omitempty"`
}

func (x *ResultElection) Reset() {
	*x = ResultElection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaccia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultElection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultElection) ProtoMessage() {}

func (x *ResultElection) ProtoReflect() protoreflect.Message {
	mi := &file_interfaccia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultElection.ProtoReflect.Descriptor instead.
func (*ResultElection) Descriptor() ([]byte, []int) {
	return file_interfaccia_proto_rawDescGZIP(), []int{1}
}

func (x *ResultElection) GetIdPeers() string {
	if x != nil {
		return x.IdPeers
	}
	return ""
}

type CheckLeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Check string `protobuf:"bytes,1,opt,name=check,proto3" json:"check,omitempty"`
}

func (x *CheckLeader) Reset() {
	*x = CheckLeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaccia_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLeader) ProtoMessage() {}

func (x *CheckLeader) ProtoReflect() protoreflect.Message {
	mi := &file_interfaccia_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLeader.ProtoReflect.Descriptor instead.
func (*CheckLeader) Descriptor() ([]byte, []int) {
	return file_interfaccia_proto_rawDescGZIP(), []int{2}
}

func (x *CheckLeader) GetCheck() string {
	if x != nil {
		return x.Check
	}
	return ""
}

// / messaggi comuni per entrambi i servizi remoti, registrazione e aggiornamento lista peer
type JSONClientRegistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port     string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	IdPeer   string `protobuf:"bytes,3,opt,name=id_peer,json=idPeer,proto3" json:"id_peer,omitempty"`
}

func (x *JSONClientRegistration) Reset() {
	*x = JSONClientRegistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaccia_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONClientRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONClientRegistration) ProtoMessage() {}

func (x *JSONClientRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_interfaccia_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONClientRegistration.ProtoReflect.Descriptor instead.
func (*JSONClientRegistration) Descriptor() ([]byte, []int) {
	return file_interfaccia_proto_rawDescGZIP(), []int{3}
}

func (x *JSONClientRegistration) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *JSONClientRegistration) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *JSONClientRegistration) GetIdPeer() string {
	if x != nil {
		return x.IdPeer
	}
	return ""
}

type JSONListPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*JSONClientRegistration `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *JSONListPeer) Reset() {
	*x = JSONListPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaccia_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONListPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONListPeer) ProtoMessage() {}

func (x *JSONListPeer) ProtoReflect() protoreflect.Message {
	mi := &file_interfaccia_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONListPeer.ProtoReflect.Descriptor instead.
func (*JSONListPeer) Descriptor() ([]byte, []int) {
	return file_interfaccia_proto_rawDescGZIP(), []int{4}
}

func (x *JSONListPeer) GetItems() []*JSONClientRegistration {
	if x != nil {
		return x.Items
	}
	return nil
}

// /////////
// /// messaggi,procedure e servizi remoti per Raft Election
type RequestElection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vote string `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Term int32  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
}

func (x *RequestElection) Reset() {
	*x = RequestElection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaccia_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestElection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestElection) ProtoMessage() {}

func (x *RequestElection) ProtoReflect() protoreflect.Message {
	mi := &file_interfaccia_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestElection.ProtoReflect.Descriptor instead.
func (*RequestElection) Descriptor() ([]byte, []int) {
	return file_interfaccia_proto_rawDescGZIP(), []int{5}
}

func (x *RequestElection) GetVote() string {
	if x != nil {
		return x.Vote
	}
	return ""
}

func (x *RequestElection) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

type AnswerElection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vote string `protobuf:"bytes,1,opt,name=vote,proto3" json:"vote,omitempty"`
}

func (x *AnswerElection) Reset() {
	*x = AnswerElection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaccia_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerElection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerElection) ProtoMessage() {}

func (x *AnswerElection) ProtoReflect() protoreflect.Message {
	mi := &file_interfaccia_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerElection.ProtoReflect.Descriptor instead.
func (*AnswerElection) Descriptor() ([]byte, []int) {
	return file_interfaccia_proto_rawDescGZIP(), []int{6}
}

func (x *AnswerElection) GetVote() string {
	if x != nil {
		return x.Vote
	}
	return ""
}

type HeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term     int32  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderID string `protobuf:"bytes,2,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
}

func (x *HeartBeat) Reset() {
	*x = HeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interfaccia_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeat) ProtoMessage() {}

func (x *HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_interfaccia_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeat.ProtoReflect.Descriptor instead.
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return file_interfaccia_proto_rawDescGZIP(), []int{7}
}

func (x *HeartBeat) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HeartBeat) GetLeaderID() string {
	if x != nil {
		return x.LeaderID
	}
	return ""
}

var File_interfaccia_proto protoreflect.FileDescriptor

var file_interfaccia_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x63, 0x69, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x33, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x70,
	0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x49,
	0x64, 0x50, 0x65, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x64, 0x5f, 0x70, 0x65,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x64, 0x50, 0x65, 0x65,
	0x72, 0x73, 0x22, 0x23, 0x0a, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x61, 0x0a, 0x16, 0x4a, 0x53, 0x4f, 0x4e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x50, 0x65, 0x65, 0x72, 0x22, 0x3d, 0x0a, 0x0c, 0x4a, 0x53,
	0x4f, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4a, 0x53, 0x4f, 0x4e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x39, 0x0a, 0x0f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x76, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x74, 0x65, 0x72, 0x6d, 0x22, 0x24, 0x0a, 0x0e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x45, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x22, 0x3b, 0x0a, 0x09, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x32, 0x9c, 0x02, 0x0a, 0x0c, 0x52, 0x69, 0x6e, 0x67,
	0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64,
	0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x0f, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x29, 0x0a,
	0x09, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x0c, 0x2e, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x1a, 0x0c, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x1a, 0x0d, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x12,
	0x35, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e,
	0x4a, 0x53, 0x4f, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x32, 0xea, 0x01, 0x0a, 0x0c, 0x52, 0x61, 0x66, 0x74, 0x45,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a,
	0x0d, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x12, 0x35,
	0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x4a,
	0x53, 0x4f, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x61, 0x66,
	0x74, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0f, 0x2e, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0d,
	0x73, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x0a, 0x2e,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x63,
	0x69, 0x61, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interfaccia_proto_rawDescOnce sync.Once
	file_interfaccia_proto_rawDescData = file_interfaccia_proto_rawDesc
)

func file_interfaccia_proto_rawDescGZIP() []byte {
	file_interfaccia_proto_rawDescOnce.Do(func() {
		file_interfaccia_proto_rawDescData = protoimpl.X.CompressGZIP(file_interfaccia_proto_rawDescData)
	})
	return file_interfaccia_proto_rawDescData
}

var file_interfaccia_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_interfaccia_proto_goTypes = []interface{}{
	(*MessageElection)(nil),        // 0: MessageElection
	(*ResultElection)(nil),         // 1: resultElection
	(*CheckLeader)(nil),            // 2: checkLeader
	(*JSONClientRegistration)(nil), // 3: JSONClientRegistration
	(*JSONListPeer)(nil),           // 4: JSONListPeer
	(*RequestElection)(nil),        // 5: RequestElection
	(*AnswerElection)(nil),         // 6: AnswerElection
	(*HeartBeat)(nil),              // 7: HeartBeat
	(*emptypb.Empty)(nil),          // 8: google.protobuf.Empty
}
var file_interfaccia_proto_depIdxs = []int32{
	3,  // 0: JSONListPeer.items:type_name -> JSONClientRegistration
	0,  // 1: RingElection.SendElection:input_type -> MessageElection
	1,  // 2: RingElection.SendResult:input_type -> resultElection
	2,  // 3: RingElection.SendCheck:input_type -> checkLeader
	3,  // 4: RingElection.SendRequest:input_type -> JSONClientRegistration
	4,  // 5: RingElection.SendUpdate:input_type -> JSONListPeer
	3,  // 6: RaftElection.SendRequest:input_type -> JSONClientRegistration
	4,  // 7: RaftElection.SendUpdate:input_type -> JSONListPeer
	5,  // 8: RaftElection.SendRaftElection:input_type -> RequestElection
	7,  // 9: RaftElection.sendHeartBeat:input_type -> HeartBeat
	8,  // 10: RingElection.SendElection:output_type -> google.protobuf.Empty
	8,  // 11: RingElection.SendResult:output_type -> google.protobuf.Empty
	2,  // 12: RingElection.SendCheck:output_type -> checkLeader
	4,  // 13: RingElection.SendRequest:output_type -> JSONListPeer
	8,  // 14: RingElection.SendUpdate:output_type -> google.protobuf.Empty
	4,  // 15: RaftElection.SendRequest:output_type -> JSONListPeer
	8,  // 16: RaftElection.SendUpdate:output_type -> google.protobuf.Empty
	6,  // 17: RaftElection.SendRaftElection:output_type -> AnswerElection
	8,  // 18: RaftElection.sendHeartBeat:output_type -> google.protobuf.Empty
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_interfaccia_proto_init() }
func file_interfaccia_proto_init() {
	if File_interfaccia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interfaccia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageElection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaccia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultElection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaccia_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckLeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaccia_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONClientRegistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaccia_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONListPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaccia_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestElection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaccia_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerElection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interfaccia_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interfaccia_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_interfaccia_proto_goTypes,
		DependencyIndexes: file_interfaccia_proto_depIdxs,
		MessageInfos:      file_interfaccia_proto_msgTypes,
	}.Build()
	File_interfaccia_proto = out.File
	file_interfaccia_proto_rawDesc = nil
	file_interfaccia_proto_goTypes = nil
	file_interfaccia_proto_depIdxs = nil
}
